### ISSUE TITLE
我用自己训练好的模型进行检测会出现 operands could not be broadcast together with shapes (1,2,8) (19200,2)问题

### ISSUE THREAD

**Issue by BroMachee** [iwanggp/yolov5-opencv-pycpp-tensorrt#1]
Traceback (most recent call last):
  File "D:/projects/python/opencv_murtaza/yolov5_opencv.py", line 210, in <module>
    dets = yolonet.detect(frame)
  File "D:/projects/python/opencv_murtaza/yolov5_opencv.py", line 146, in detect
    self.grid[i], (self.na, 1))) * int(self.stride[i])
ValueError: operands could not be broadcast together with shapes (1,2,8) (19200,2)
[ WARN:0@2.885] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~Sourc
eReaderCB terminating async callback

这个是报错的信息，请问是我的训练参数的问题吗？
我直接用官方的yolov5s.pt模型训练出来的yolov5s.onnx拿进去你的代码中跑也是同样的问题

**Comment by BroMachee** [comment]
用你提供的的yolov5s.onnx不会有这个问题

**Comment by Timskt** [comment]
> 

老哥请问你解决了吗？

**Comment by iwanggp** [comment]
转ONNX模型需要修改源码的，不能直接转的。

**Comment by I-love-study** [comment]
> 转ONNX模型需要修改源码的，不能直接转的。

请问一下，修改源码具体是修改哪些地方
是否有相关教程能够参考一下

**Comment by iwanggp** [comment]
请参考这篇文章，将源码修改一下再转ONNX。https://baijiahao.baidu.com/s?id=1711380345827267922&wfr=spider&for=pc

**Comment by Timskt** [comment]
> 请参考这篇文章，将源码修改一下再转ONNX。https://baijiahao.baidu.com/s?id=1711380345827267922&wfr=spider&for=pc

我已经解决了这个问题了，其实yolo官方的代码提供了转onnx的代码了，还是谢谢老哥回答

**Comment by iwanggp** [comment]
直接转ONNX是不行的，激活函数不支持，输出的形状也不对。需要修改源码的

**Comment by Timskt** [comment]
> 直接转ONNX是不行的，激活函数不支持，输出的形状也不对。需要修改源码的

这样子啊，谢谢老哥，那我先把这篇文章收藏一下，等以后有需求再看，我最后的做法是利用detect.py里面提供的代码魔改了一下读取的模型，然后opencv做输入，也实现了我要的效果。
以下是我的代码:
```python
import cv2
import numpy as np
import torch
from PyQt5 import QtGui
from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtGui import QImage
from torch.backends import cudnn

from experimental import attempt_load
from utils.datasets import letterbox
from utils.general import check_img_size, non_max_suppression, scale_coords
from utils.plots import plot_one_box
from utils.torch_utils import select_device


class LoadYoloThread(QThread):

    result = pyqtSignal(QImage,list)

    def __init__(self,image=None):
        super(LoadYoloThread, self).__init__()
        self.image = image

        parser = argparse.ArgumentParser()
        parser.add_argument('--weights', nargs='+', type=str,
                            default='best.pt', help='model.pt path(s)')
        # file/folder, 0 for webcam
        parser.add_argument('--source', type=str,
                            default='data/images', help='source')
        parser.add_argument('--img-size', type=int,
                            default=640, help='inference size (pixels)')
        parser.add_argument('--conf-thres', type=float,
                            default=0.25, help='object confidence threshold')
        parser.add_argument('--iou-thres', type=float,
                            default=0.45, help='IOU threshold for NMS')
        parser.add_argument('--device', default='',
                            help='cuda device, i.e. 0 or 0,1,2,3 or cpu')
        parser.add_argument(
            '--view-img', action='store_true', help='display results')
        parser.add_argument('--save-txt', action='store_true',
                            help='save results to *.txt')
        parser.add_argument('--save-conf', action='store_true',
                            help='save confidences in --save-txt labels')
        parser.add_argument('--nosave', action='store_true',
                            help='do not save images/videos')
        parser.add_argument('--classes', nargs='+', type=int,
                            help='filter by class: --class 0, or --class 0 2 3')
        parser.add_argument(
            '--agnostic-nms', action='store_true', help='class-agnostic NMS')
        parser.add_argument('--augment', action='store_true',
                            help='augmented inference')
        parser.add_argument('--update', action='store_true',
                            help='update all models')
        parser.add_argument('--project', default='runs/detect',
                            help='save results to project/name')
        parser.add_argument('--name', default='exp',
                            help='save results to project/name')
        parser.add_argument('--exist-ok', action='store_true',
                            help='existing project/name ok, do not increment')
        self.parser = parser
        self.opt = parser.parse_args()
        print(self.opt)

        source, weights, view_img, save_txt, imgsz = self.opt.source, self.opt.weights, self.opt.view_img, self.opt.save_txt, self.opt.img_size

        self.device = select_device(self.opt.device)
        self.half = self.device.type != 'cpu'  # half precision only supported on CUDA

        cudnn.benchmark = True

        # Load model
        self.model = attempt_load(
            weights, map_location=self.device)  # load FP32 model
        stride = int(self.model.stride.max())  # model stride
        self.imgsz = check_img_size(imgsz, s=stride)  # check img_size
        if self.half:
            self.model.half()  # to FP16

        # Get names and colors
        self.names = self.model.module.names if hasattr(
            self.model, 'module') else self.model.names
        self.colors = [[random.randint(0, 255)
                        for _ in range(3)] for _ in self.names]

    def setImage(self,image):
        self.image = image

    def run(self):
            img = self.image
            name_list = []
            test_list = []
            if img is not None:
                showimg = img
                with torch.no_grad():
                    img = letterbox(img, new_shape=self.opt.img_size)[0]
                    # Convert
                    # BGR to RGB, to 3x416x416
                    img = img[:, :, ::-1].transpose(2, 0, 1)
                    img = np.ascontiguousarray(img)
                    img = torch.from_numpy(img).to(self.device)
                    img = img.half() if self.half else img.float()  # uint8 to fp16/32
                    img /= 255.0  # 0 - 255 to 0.0 - 1.0
                    if img.ndimension() == 3:
                        img = img.unsqueeze(0)
                    # Inference
                    pred = self.model(img, augment=self.opt.augment)[0]

                    # Apply NMS
                    pred = non_max_suppression(pred, self.opt.conf_thres, self.opt.iou_thres, classes=self.opt.classes,
                                               agnostic=self.opt.agnostic_nms)
                    # Process detections
                    for i, det in enumerate(pred):  # detections per image
                        if det is not None and len(det):
                            # Rescale boxes from img_size to im0 size
                            det[:, :4] = scale_coords(
                                img.shape[2:], det[:, :4], showimg.shape).round()
                            # Write results
                            for *xyxy, conf, cls in reversed(det):
                                label = '%s %.2f' % (self.names[int(cls)], conf)
                                name_list.append(self.names[int(cls)])
                                test_list.append([self.names[int(cls)],label,xyxy])
                                print(label)
                                plot_one_box(
                                    xyxy, showimg, label=label, color=self.colors[int(cls)], line_thickness=2)

                self.out.write(showimg)
                show = cv2.resize(showimg, (640, 480))
                self.result = cv2.cvtColor(show, cv2.COLOR_BGR2RGB)
                showImage = QtGui.QImage(self.result.data, self.result.shape[1], self.result.shape[0],
                                         QtGui.QImage.Format_RGB888)
                # self.label.setPixmap(QtGui.QPixmap.fromImage(showImage))
                self.result.emit(QImage(showImage),test_list)
```
